[build]
# Optimize for memory usage during cross-compilation
codegen-units = 1

[target.x86_64-unknown-linux-gnu]
linker = "x86_64-linux-gnu-gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"

[net]
git-fetch-with-cli = true
retry = 5

[http]
timeout = 60
multiplexing = false
check-revoke = false

[profile.release]
codegen-units = 1
opt-level = 1
debug = false
strip = "symbols"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"