[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-ar"

[target.x86_64-unknown-linux-gnu]
linker = "gcc"
rustflags = ["-C", "target-feature=-crt-static"]

[build]
# Optimize development builds
rustflags = ["-C", "opt-level=1", "-C", "link-args=-lresolv"]

[profile.dev]
# Faster builds in development
opt-level = 1
debug = true
split-debuginfo = "unpacked"
incremental = true

[profile.dev.package."*"]
# Don't optimize dependencies in dev builds
opt-level = 0

[profile.release]
# Control memory usage in release builds
codegen-units = 16
lto = "thin"
panic = "abort"

[env]
PKG_CONFIG_ALLOW_CROSS = "1"
CARGO_NET_GIT_FETCH_WITH_CLI = "true"