name: "Automatic Release"

on:
  push:
    tags:
      - 'v*' # Se activa cuando se crea un tag que empiece con v

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # Checkout del repositorio público
      - name: Checkout public repository
        uses: actions/checkout@v4
        with:
          repository: kristiangarcia/luminakraft-launcher-releases
          path: ../luminakraft-launcher-releases
          token: ${{ secrets.PUBLIC_REPO_TOKEN }}
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        
      - name: Install dependencies
        run: npm install
        
      - name: Run auto-release script
        run: node scripts/auto-release.js
        env:
          GITHUB_TOKEN: ${{ secrets.PUBLIC_REPO_TOKEN }} 